import { customAlphabet } from 'nanoid/non-secure';
import { ValidationResult, Validator } from './validation';

const idPattern = /^[a-z](?:[-_a-z\d]*[a-z\d])?$/;

const alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789-_';
const nanoid = customAlphabet(alphabet, 10);

/**
 * Validation rules of IDs:
 * - Only use a-z, 0-9, and - or _
 * - No spaces
 * - No uppercase
 * - No leading digits
 * - Length limit: 64 characters
 * - No special characters
 * - No trailing hyphens/underscores
 */
export const idValidator: Validator<string> = (value: string): ValidationResult => {
  if (value.length === 0) {
    return ValidationResult.invalid("Id shouldn't be empty");
  } else if (value.length > 64) {
    return ValidationResult.invalid("Id shouldn't exceed 64 characters");
  }

  if (idPattern.test(value)) {
    return ValidationResult.valid();
  } else {
    return ValidationResult.invalid(
      `Id do not respect any of following the rules:
          - Only use a-z, 0-9, and - or _
          - No spaces
          - No uppercase
          - No leading digits
          - No special characters
          - No trailing hyphens/underscores`,
    );
  }
};

export function generateId(prefix: string): string {
  return `${prefix}${nanoid()}i`; // add suffix 'i' to avoid trailing hyphen/underscore generated by nanoid
}

export function idFromString(str: string): string {
  let value = str
    // ASCII folding: é -> e, ü -> u, etc.
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    // Keep only a-z, 0-9, - and _
    .replace(/[^a-z0-9_-]/g, '_');

  if (!/^[a-z]/.test(value)) {
    value = `i${value}`;
  }

  value = value.slice(0, 64);

  if (/[-_]$/.test(value)) {
    value = `${value.slice(0, -1)}i`;
  }

  return value;
}
